version: "3"
services:
  db:
      container_name: postgres_container
      image: postgres:latest
      environment:
        POSTGRES_DB: "testServer"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "admin"
        PGDATA: "/var/lib/postgresql/data/pgdata"
      ports:
        - "5432:5432"
      volumes:
        - ./server/database/:/docker-entrypoint-initdb.d
        - pg-data:/var/lib/postgresql/data
      networks:
        - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
volumes:
  pg-data:
  pgadmin-data:
networks:
  postgres:
    driver: bridge